// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqs-OXBoAoS576zRL_V2IR6QYHxcZFWjM',
    appId: '1:370111494926:web:0bafb076acdd6c7706b55f',
    messagingSenderId: '370111494926',
    projectId: 'salesmanagementfluttermovildem',
    authDomain: 'salesmanagementfluttermovildem.firebaseapp.com',
    storageBucket: 'salesmanagementfluttermovildem.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm32bQjNf8_Q0-Y2JlvjiVlB7zhabbqSs',
    appId: '1:370111494926:android:08acc2e91c3e2e4f06b55f',
    messagingSenderId: '370111494926',
    projectId: 'salesmanagementfluttermovildem',
    storageBucket: 'salesmanagementfluttermovildem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWRDEBKdMc_-4sBLc3asy8_N6YwoYMiao',
    appId: '1:370111494926:ios:688e07296f6c7ae006b55f',
    messagingSenderId: '370111494926',
    projectId: 'salesmanagementfluttermovildem',
    storageBucket: 'salesmanagementfluttermovildem.firebasestorage.app',
    iosBundleId: 'com.example.salesExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWRDEBKdMc_-4sBLc3asy8_N6YwoYMiao',
    appId: '1:370111494926:ios:688e07296f6c7ae006b55f',
    messagingSenderId: '370111494926',
    projectId: 'salesmanagementfluttermovildem',
    storageBucket: 'salesmanagementfluttermovildem.firebasestorage.app',
    iosBundleId: 'com.example.salesExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqs-OXBoAoS576zRL_V2IR6QYHxcZFWjM',
    appId: '1:370111494926:web:9c0c208f15c4707b06b55f',
    messagingSenderId: '370111494926',
    projectId: 'salesmanagementfluttermovildem',
    authDomain: 'salesmanagementfluttermovildem.firebaseapp.com',
    storageBucket: 'salesmanagementfluttermovildem.firebasestorage.app',
  );
}
